const constants = {
	SHOW_ADD_USER_FORM: 'SHOW_ADD_USER_FORM',
	SHOW_TOGGLE_VISIBLE_BLOCK: 'SHOW_TOGGLE_VISIBLE_BLOCK',

	TOGGLE_COLUMN_VISIBILITY: 'TOGGLE_COLUMN_VISIBILITY',
	ADD_NEW_USER_INFO: 'ADD_NEW_USER_INFO'

}

export default constants;